#define T_EOF		0
#define T_SPC		1
#define T_PROG		2
#define T_VARS		3
#define T_CHAR		4
#define T_INT		5
#define T_STRCT		6
#define T_ESTRCT	7
#define T_TDEF		8
#define T_PRINT		9
#define T_IF		10
#define T_ENDIF		11
#define T_WHILE		12
#define T_EWHILE	13
#define T_ELSE		14
#define T_ELSEIF	15
#define T_FOR		16
#define T_TO		17
#define T_STEP		18
#define T_ENDFOR	19
#define T_SMAIN		20
#define T_EMAIN		21
#define T_FUNCT		22
#define T_EFUNCT	23
#define T_RETURN	24
#define T_SWITCH	25
#define T_CASE		26
#define T_DEF		27
#define T_ESWITCH	28
#define T_BREAK		29
#define T_AND		30
#define T_OR		31
#define T_WORD		32
#define T_NUMBER	33
#define	T_GREATER	34
#define T_SMALLER	35
#define T_EQUAL		36
#define T_NEQUAL	37
#define	T_PLUS		38
#define	T_MINUS		39
#define	T_POWER		40
#define	T_MULT		41
#define	T_COMMENT	42
#define	T_DIV		43
#define	T_LBRACE	44
#define T_RBRACE	45
#define T_LBRACKET	46
#define T_RBRACKET	47
#define T_LPARENTH	48
#define T_RPARENTH	49
#define T_SEMICOL	50
#define T_DOT		51
#define T_COMMA		52
#define	T_NEWLINE	53
#define T_UNKNWON 	54
#define T_THEN      55
#define T_ASSIGN    56
#define T_COL       57
#define T_LETTER    58
#define T_ID        59
#define T_DIGIT     60
#define T_LETTER    61